#!/usr/bin/env bash
# do-docker4.sh — wrapper that builds docker images for AQY/ASY/AUY/AIY
# - AQY/ASY/AUY: pristine env (no toolchain overrides), no modifications
# - AIY: keep same env behavior as do-genesis.sh and build aiy-node (not sui-node)
#        also patch aiy-sdk-types E0658 (.is_multiple_of) during docker build only
set -euo pipefail

: "${GH_USER:=ab2bc}"  # default GitHub user for GHCR
export GH_USER

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${SCRIPT_DIR}"

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing dependency: $1" >&2; exit 1; }
}

check_docker() {
  if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker daemon not reachable. Start Docker and re-run." >&2
    exit 1
  fi
}

detect_engine() {
  local p="$ROOT/do-docker.sh"
  [[ -x "$p" ]] && echo "$p" && return 0
  [[ -f "$p" ]] && chmod +x "$p" && echo "$p" && return 0
  echo ""
}

ensure_dockerignore() {
  local dir="$1"
  local file="$dir/.dockerignore"
  cat > "$file" <<'EOF'
# Autogenerated by do-docker4.sh to keep Git worktree metadata out of the Docker context
.git
.gitmodules
**/.git
**/.gitmodules

# Rust targets
target
**/target

# Node / npm (if any)
node_modules
**/node_modules

# Logs & temp
*.log
*.tmp
EOF
}

# ---- AIY-specific fix for stale bytecode snapshots ----
clean_aiy_stale_bytecode() {
  local proj_dir="$1"
  local snapshot_dir="${proj_dir}/crates/aiy-framework-snapshot/bytecode_snapshot"
  local cleaned_anything=false
  
  # Remove main bytecode snapshots (don't backup, just remove)
  if [[ -d "$snapshot_dir" ]]; then
    echo "[$flavor] Removing stale bytecode snapshots before build"
    rm -rf "$snapshot_dir" || {
      echo "[$flavor] WARNING: Failed to remove snapshot directory; continuing anyway"
    }
    cleaned_anything=true
  fi
  
  # Clear any Move build directories that might contain stale sui references
  local build_dirs
  mapfile -t build_dirs < <(find "${proj_dir}/crates/aiy-framework/packages" -name "build" -type d 2>/dev/null)
  for build_dir in "${build_dirs[@]}"; do
    if [[ -d "$build_dir" ]]; then
      echo "[$flavor] Removing stale Move build directory: $build_dir"
      rm -rf "$build_dir" || echo "[$flavor] WARNING: Failed to remove build directory: $build_dir"
      cleaned_anything=true
    fi
  done
  
  # Clear target directory fingerprints that might be stale
  local target_snapshots
  mapfile -t target_snapshots < <(find "${proj_dir}/target" -name "*framework-snapshot*" -type d 2>/dev/null)
  for target_dir in "${target_snapshots[@]}"; do
    if [[ -d "$target_dir" ]]; then
      echo "[$flavor] Removing stale target snapshot: $target_dir"
      rm -rf "$target_dir" || echo "[$flavor] WARNING: Failed to remove target snapshot: $target_dir"
      cleaned_anything=true
    fi
  done
  
  # Also remove any backup snapshots from previous runs
  local backup_dir="${proj_dir}/crates/aiy-framework-snapshot/bytecode_snapshot.backup"
  if [[ -d "$backup_dir" ]]; then
    echo "[$flavor] Removing backup snapshots from previous runs"
    rm -rf "$backup_dir" || echo "[$flavor] WARNING: Failed to remove backup snapshot directory"
    cleaned_anything=true
  fi
  
  if [[ "$cleaned_anything" == "true" ]]; then
    echo "[$flavor] Cleaned stale bytecode to ensure fresh build"
    return 0
  else
    echo "[$flavor] No stale bytecode found"
    return 1
  fi
}

pick_dockerfile() {
  # args: flavor repo_dir
  local flavor="$1"
  local repo_dir="$2"

  local top_df="$ROOT/Dockerfile.$flavor"
  local ab2bc_df="$ROOT/ab2bc/$flavor/Dockerfile"
  local repo_df="$repo_dir/Dockerfile"

  if [[ -f "$top_df" ]]; then
    echo "$top_df"
  elif [[ -f "$ab2bc_df" ]]; then
    echo "$ab2bc_df"
  elif [[ -f "$repo_df" ]]; then
    echo "$repo_df"
  else
    echo ""
  fi
}

aiy_wrap_dockerfile() {
  # Create a temporary Dockerfile for AIY that:
  #  1) builds aiy-node instead of sui-node
  #  2) injects a pre-build patch fixing unstable `.is_multiple_of(8)` (E0658)
  # args: dockerfile repo_dir
  local src_df="$1"
  local repo_dir="$2"
  local tmp_df="$repo_dir/.Dockerfile.aiy.tmp"

  # Start from the source Dockerfile
  cp -f "$src_df" "$tmp_df"

  # Rename sui-node -> aiy-node everywhere (AIY only)
  sed -i -E 's/--bin[[:space:]]+sui-node/--bin aiy-node/g' "$tmp_df"
  sed -i -E 's#target/release/sui-node#target/release/aiy-node#g' "$tmp_df"
  sed -i -E 's#/out/sui-node#/out/aiy-node#g' "$tmp_df"

  # Inject a surgical patch BEFORE the first `cargo build --release --bin aiy-node`.
  # We replace the first occurrence with a sequence that fetches sources, patches
  # aiy-sdk-types (unstable .is_multiple_of), then runs the build.
  local repl='cargo fetch --locked || cargo fetch; '\
'echo "Patching aiy-sdk-types for stable Rust (.is_multiple_of(8) -> %8==0)"; '\
'find /usr/local/cargo/git/checkouts -type f -path "*/aiy-sdk-types*/src/crypto/zklogin.rs" -print -exec sed -i -E "s/\\\.len\\\(\\\)\\\.is_multiple_of\\\(\\\s*8\\\s*\\\)/.len() % 8 == 0/g" {} + ; '\
'cargo build --release --bin aiy-node'

  # Replace only the FIRST match to keep it minimal/surgical.
  # Use awk to do a one-shot substitution.
  awk -v needle='cargo build --release --bin aiy-node' -v repl="$repl" '
    BEGIN{done=0}
    {
      if(!done){
        i=index($0, needle);
        if(i){
          pre=substr($0, 1, i-1);
          post=substr($0, i+length(needle));
          print pre repl post;
          done=1;
          next
        }
      }
      print
    }
  ' "$tmp_df" > "$tmp_df.tmp" && mv "$tmp_df.tmp" "$tmp_df"

  echo "$tmp_df"
}

prepare_env_for_flavor() {
  # Pristine for AQY/ASY/AUY; AIY mirrors do-genesis toolchain override if present.
  local flavor="$1"
  local repo_dir="${ROOT}/${flavor}"
  case "$flavor" in
    AIY)
      if command -v rustup >/dev/null 2>&1; then
        ( cd "$repo_dir" 2>/dev/null && rustup override set 1.89.0 >/dev/null 2>&1 ) || true
      fi
      export AIY_ENV=1
      ;;
    AQY|ASY|AUY)
      if command -v rustup >/dev/null 2>&1; then
        ( cd "$repo_dir" 2>/dev/null && rustup override unset >/dev/null 2>&1 ) || true
      fi
      unset AIY_ENV || true
      ;;
  esac
}

run_one_flavor() {
  local flavor="$1"; shift || true
  local engine_args=("$@")

  local flavor_lc; flavor_lc="$(echo "$flavor" | tr '[:upper:]' '[:lower:]')"
  local repo_dir="$ROOT/$flavor"
  local dockerfile; dockerfile="$(pick_dockerfile "$flavor" "$repo_dir")" || true

  # For AIY only: ensure Dockerfile compiles the correct node binary (aiy-node)
  if [[ "$flavor" == "AIY" && -n "${dockerfile:-}" && -f "$dockerfile" ]]; then
    dockerfile="$(aiy_wrap_dockerfile "$dockerfile" "$repo_dir")"
  fi

  local local_image="${flavor_lc}/node"
  local ghcr_image="ghcr.io/${GH_USER}/${flavor_lc}-node"
  local repo_slug="${GH_USER}/$flavor"
  local log="$ROOT/build-${flavor_lc}.log"

  echo ""
  echo "========== [$flavor] =========="
  echo "REPO_DIR:    $repo_dir"
  echo "DOCKERFILE:  ${dockerfile:-<not found>}"
  echo "LOCAL_IMAGE: $local_image"
  echo "GHCR_IMAGE:  $ghcr_image"
  echo "REPO_SLUG:   $repo_slug"

  if [[ -z "$dockerfile" ]]; then
    echo "[$flavor] ERROR: Dockerfile not found (looked for: $ROOT/Dockerfile.$flavor, $ROOT/ab2bc/$flavor/Dockerfile, $repo_dir/Dockerfile)"
    return 1
  fi

  echo "==> Repo: $repo_dir"
  echo "==> Using Dockerfile: $dockerfile"
  prepare_env_for_flavor "$flavor"
  ensure_dockerignore "$repo_dir"
  
  # Clean stale bytecode before Docker build for AIY
  if [[ "$flavor" == "AIY" ]]; then
    clean_aiy_stale_bytecode "$repo_dir"
  fi
  
  echo "==> Building Docker image locally (gated step)"

  local rc=0
  set +e
  (
    export REPO_DIR="$repo_dir" DOCKERFILE="$dockerfile" LOCAL_IMAGE="$local_image" GHCR_IMAGE="$ghcr_image" REPO_SLUG="$repo_slug"
    export SKIP_GIT="${SKIP_GIT:-1}"
    cd "$repo_dir" 2>/dev/null || true
    exec "$DO_ENGINE" "${engine_args[@]}"
  ) 2>&1 | tee "$log"
  rc="${PIPESTATUS[0]}"
  set -e

  if (( rc == 0 )); then
    echo "[$flavor] OK."
  else
    echo "[$flavor] FAILED (rc=$rc). See $log"
  fi
  return "$rc"
}

main() {
  need docker
  check_docker

  DO_ENGINE="$(detect_engine)"
  if [[ -z "$DO_ENGINE" ]]; then
    echo "ERROR: do-docker.sh not found next to this wrapper: $ROOT" >&2
    exit 1
  fi

  # Default flavors; allow a single positional to filter
  FLAVORS=(AQY ASY AUY AIY)
  if (( $# >= 1 )); then
    case "$1" in
      AQY|ASY|AUY|AIY) FLAVORS=("$1"); shift ;;
    esac
  fi

  ENGINE_ARGS=("$@")

  local failed=0
  for f in "${FLAVORS[@]}"; do
    if ! run_one_flavor "$f" "${ENGINE_ARGS[@]}"; then
      failed=1
    fi
  done

  echo ""
  echo "========== SUMMARY =========="
  if (( failed )); then
    echo "Some builds failed."
    exit 1
  else
    echo "All builds completed."
  fi
}

main "$@"
