[package]
name = "testnet_soulbound_nft"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Aiy = { local = "../../../crates/aiy-framework/packages/aiy-framework" }

[addresses]
examples = "0x0"
