[package]
name = "shared_no_tto"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Aiy = { local = "../../../../crates/aiy-framework/packages/aiy-framework" }
common = { local = "../common" }

[addresses]
shared_no_tto = "0x0"
