[package]
name = "test-cluster"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tokio-util.workspace = true
rand.workspace = true
tempfile.workspace = true
aiy-config.workspace = true
aiy-core.workspace = true
mysten-common.workspace = true
aiy-framework.workspace = true
aiy-swarm-config.workspace = true
aiy-indexer.workspace = true
aiy-json-rpc.workspace = true
aiy-json-rpc-types.workspace = true
aiy-json-rpc-api.workspace = true
aiy-node.workspace = true
aiy-pg-db.workspace = true
aiy-protocol-config.workspace = true
aiy-swarm.workspace = true
aiy-types.workspace = true
prometheus.workspace = true
aiy-keys.workspace = true
aiy-sdk.workspace = true
aiy-test-transaction-builder.workspace = true

move-binary-format.workspace = true

[target.'cfg(msim)'.dependencies]
aiy-simulator.workspace = true
fastcrypto-zkp.workspace = true

[dev-dependencies]
aiy-json-rpc-api.workspace = true
aiy-macros.workspace = true
