---
version: "3.9"
services:
  fullnode:
    # Note: Update the tag to the latest version of mysten/aiy-node for mainnet or testnet.
    image: mysten/aiy-node:mainnet-v1.19.1
    ports:
    - "8080:8080"
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/opt/aiy/config/fullnode.yaml:ro
    - ./genesis.blob:/opt/aiy/config/genesis.blob:ro
    - ./aiydb:/opt/aiy/db:rw
    command: ["/opt/aiy/bin/aiy-node", "--config-path", "/opt/aiy/config/fullnode.yaml"]
volumes:
  aiydb:
