[package]
name = "aiy-indexer-alt-graphql"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "aiy-indexer-alt-graphql"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-graphql = { workspace = true, features = ["dataloader"] }
async-graphql-axum.workspace = true
async-graphql-value.workspace = true
async-trait.workspace = true
# axum.workspace = true
# axum-extra.workspace = true
axum = { version = "0.7", default-features = false, features = [ "macros", "tokio", "http1", "http2", "json", "matched-path", "original-uri", "form", "query", "ws", ] }
axum-extra = { version = "0.9", features = ["typed-header"] }
bcs.workspace = true
chrono.workspace = true
clap.workspace = true
const-str.workspace = true
diesel.workspace = true
diesel-async.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
futures.workspace = true
headers.workspace = true
im.workspace = true
itertools.workspace = true
pin-project.workspace = true
prometheus.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
shared-crypto.workspace = true
telemetry-subscribers.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true

bin-version.workspace = true
aiy-default-config.workspace = true
aiy-display.workspace = true
aiy-indexer-alt-metrics.workspace = true
aiy-indexer-alt-reader.workspace = true
aiy-indexer-alt-schema.workspace = true
aiy-name-service.workspace = true
aiy-package-resolver.workspace = true
aiy-pg-db.workspace = true
aiy-protocol-config.workspace = true
aiy-rpc.workspace = true
aiy-rpc-api.workspace = true
aiy-sdk-types.workspace = true
aiy-sql-macro.workspace = true
aiy-types.workspace = true

[dev-dependencies]
insta.workspace = true

[features]
staging = []
