[package]
name = "BridgedKa"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../../crates/aiy-framework/packages/move-stdlib" }
Aiy = { local = "../../../../../crates/aiy-framework/packages/aiy-framework" }

[addresses]
bridged_ka = "0x0"
