[package]
name = "Locked Stake"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Aiy = { local = "../../../crates/aiy-framework/packages/aiy-framework" }
AiySystem = { local = "../../../crates/aiy-framework/packages/aiy-system" }

[addresses]
locked_stake = "0x0"
