[package]
name = "reviews_rating"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Aiy = { local = "../../../crates/aiy-framework/packages/aiy-framework", override = true }

[addresses]
reviews_rating =  "0x0"
